server:
  port: 8081
  tomcat:
    max-threads: 800
    max-http-header-size: 8192
    uri-encoding: UTF-8


spring:
  datasource:
    druid:
      username: ICARD
      password: ICARD
      url: jdbc:oracle:thin:@120.78.151.34:1521:orcl
